// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWG066XBuTv-QhVetTE2BczX68FrLTZQY',
    appId: '1:1015533447784:web:60dedb49f7f07ad97529dd',
    messagingSenderId: '1015533447784',
    projectId: 'hafta5-7c4c7',
    authDomain: 'hafta5-7c4c7.firebaseapp.com',
    storageBucket: 'hafta5-7c4c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEN5qvr2kGZ7XMuhKPQQ3I07Hb4mUdXxE',
    appId: '1:1015533447784:android:0d79fb99711647217529dd',
    messagingSenderId: '1015533447784',
    projectId: 'hafta5-7c4c7',
    storageBucket: 'hafta5-7c4c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrnn3hIUbjIpGLtJEurGgUmgws4iUQLI',
    appId: '1:1015533447784:ios:07668d1f60195d097529dd',
    messagingSenderId: '1015533447784',
    projectId: 'hafta5-7c4c7',
    storageBucket: 'hafta5-7c4c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyrnn3hIUbjIpGLtJEurGgUmgws4iUQLI',
    appId: '1:1015533447784:ios:07668d1f60195d097529dd',
    messagingSenderId: '1015533447784',
    projectId: 'hafta5-7c4c7',
    storageBucket: 'hafta5-7c4c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_f5DfiAuaxSi7-O-RXAPKWGcQfsd1OGE',
    appId: '1:1015533447784:web:536b6760a635e4067529dd',
    messagingSenderId: '1015533447784',
    projectId: 'hafta5-7c4c7',
    authDomain: 'hafta5-7c4c7.firebaseapp.com',
    storageBucket: 'hafta5-7c4c7.firebasestorage.app',
  );
}
